-- 电商工作台建表脚本
CREATE DATABASE IF NOT EXISTS ec_workbench DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE ec_workbench;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS sys_user;
CREATE TABLE sys_user (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  merchant_id BIGINT UNSIGNED NOT NULL DEFAULT 1,
  username VARCHAR(64) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  nickname VARCHAR(64) DEFAULT NULL,
  real_name VARCHAR(64) DEFAULT NULL,
  mobile VARCHAR(20) DEFAULT NULL,
  email VARCHAR(128) DEFAULT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  last_login_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updated_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_user (merchant_id, username, is_deleted)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS sys_role;
CREATE TABLE sys_role (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  merchant_id BIGINT UNSIGNED NOT NULL DEFAULT 1,
  role_name VARCHAR(64) NOT NULL,
  role_code VARCHAR(64) NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updated_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_role (merchant_id, role_code, is_deleted)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS sys_menu;
CREATE TABLE sys_menu (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  merchant_id BIGINT UNSIGNED NOT NULL DEFAULT 1,
  parent_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  menu_name VARCHAR(100) NOT NULL,
  menu_type TINYINT NOT NULL,
  route_path VARCHAR(200) DEFAULT NULL,
  perms VARCHAR(200) DEFAULT NULL,
  sort_no INT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updated_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS sys_user_role;
CREATE TABLE sys_user_role (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  merchant_id BIGINT UNSIGNED NOT NULL DEFAULT 1,
  user_id BIGINT UNSIGNED NOT NULL,
  role_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_user_role (merchant_id, user_id, role_id)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS sys_role_menu;
CREATE TABLE sys_role_menu (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  merchant_id BIGINT UNSIGNED NOT NULL DEFAULT 1,
  role_id BIGINT UNSIGNED NOT NULL,
  menu_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_role_menu (merchant_id, role_id, menu_id)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS product_category;
CREATE TABLE product_category (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  merchant_id BIGINT UNSIGNED NOT NULL DEFAULT 1,
  parent_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  category_name VARCHAR(100) NOT NULL,
  category_code VARCHAR(64) NOT NULL,
  level_no TINYINT NOT NULL DEFAULT 1,
  tree_path VARCHAR(255) DEFAULT '/',
  sort_no INT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  remark VARCHAR(255) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updated_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_cat_code (merchant_id, category_code, is_deleted)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS product;
CREATE TABLE product (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  merchant_id BIGINT UNSIGNED NOT NULL DEFAULT 1,
  product_no VARCHAR(64) NOT NULL,
  category_id BIGINT UNSIGNED NOT NULL,
  product_name VARCHAR(200) NOT NULL,
  sub_title VARCHAR(255) DEFAULT NULL,
  brand_name VARCHAR(100) DEFAULT NULL,
  unit_name VARCHAR(20) NOT NULL DEFAULT '件',
  main_image VARCHAR(255) DEFAULT NULL,
  sale_price DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  cost_price DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  market_price DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  stock_quantity INT NOT NULL DEFAULT 0,
  stock_locked INT NOT NULL DEFAULT 0,
  stock_warn_threshold INT NOT NULL DEFAULT 10,
  sale_count INT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 2,
  audit_status TINYINT NOT NULL DEFAULT 1,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  remark VARCHAR(255) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updated_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_product_no (merchant_id, product_no, is_deleted),
  KEY idx_prod_cat (category_id)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS orders;
CREATE TABLE orders (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  merchant_id BIGINT UNSIGNED NOT NULL DEFAULT 1,
  order_no VARCHAR(64) NOT NULL,
  order_status TINYINT NOT NULL DEFAULT 0,
  pay_status TINYINT NOT NULL DEFAULT 0,
  delivery_status TINYINT NOT NULL DEFAULT 0,
  customer_name VARCHAR(100) DEFAULT NULL,
  customer_mobile VARCHAR(20) DEFAULT NULL,
  receiver_name VARCHAR(100) NOT NULL,
  receiver_mobile VARCHAR(20) NOT NULL,
  address_detail VARCHAR(255) NOT NULL,
  total_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  payable_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  paid_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  seller_remark VARCHAR(255) DEFAULT NULL,
  delivery_time DATETIME DEFAULT NULL,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updated_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_order_no (merchant_id, order_no, is_deleted)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS order_item;
CREATE TABLE order_item (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  merchant_id BIGINT UNSIGNED NOT NULL DEFAULT 1,
  order_id BIGINT UNSIGNED NOT NULL,
  order_no VARCHAR(64) NOT NULL,
  product_id BIGINT UNSIGNED DEFAULT NULL,
  product_no VARCHAR(64) NOT NULL,
  product_name VARCHAR(200) NOT NULL,
  sku_attr VARCHAR(255) DEFAULT NULL,
  unit_price DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  quantity INT NOT NULL DEFAULT 1,
  line_total_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  item_status TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_order_item (order_id)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS inventory_record;
CREATE TABLE inventory_record (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  merchant_id BIGINT UNSIGNED NOT NULL DEFAULT 1,
  record_no VARCHAR(64) NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  biz_type TINYINT NOT NULL,
  biz_no VARCHAR(64) DEFAULT NULL,
  change_qty INT NOT NULL,
  stock_before INT NOT NULL,
  stock_after INT NOT NULL,
  operator_id BIGINT UNSIGNED DEFAULT NULL,
  operate_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  remark VARCHAR(255) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_record_no (merchant_id, record_no)
) ENGINE=InnoDB;

SET FOREIGN_KEY_CHECKS = 1;
